export default function Head() {
  return (
    <>
      <title>Aryan Karani</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="google-site-verification"
        content="ifqq9Z08vZAWb8Z59xVhuA42IfNdrT5-nhyuua35ZlQ"
      />
    </>
  );
}
